// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4iXjPXR8R2IJ7WqySW1yQL27mtU_Kav4',
    appId: '1:832180320682:web:978b3556159cb5070893d3',
    messagingSenderId: '832180320682',
    projectId: 'callyoo-2b8ca',
    authDomain: 'callyoo-2b8ca.firebaseapp.com',
    storageBucket: 'callyoo-2b8ca.appspot.com',
    measurementId: 'G-HVJS65DFQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJejHqn3ZXGrV7PJPosovD6_BjRfuyFN4',
    appId: '1:832180320682:android:4a1626d6abd3d5ac0893d3',
    messagingSenderId: '832180320682',
    projectId: 'callyoo-2b8ca',
    storageBucket: 'callyoo-2b8ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzIT756-4mtTH6ynkoGXpN9Tdc67mxhB4',
    appId: '1:832180320682:ios:d03d8fea59443fdf0893d3',
    messagingSenderId: '832180320682',
    projectId: 'callyoo-2b8ca',
    storageBucket: 'callyoo-2b8ca.appspot.com',
    iosClientId: '832180320682-565mve6f6uebdve1l0moq7o0dc20p16e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzIT756-4mtTH6ynkoGXpN9Tdc67mxhB4',
    appId: '1:832180320682:ios:d03d8fea59443fdf0893d3',
    messagingSenderId: '832180320682',
    projectId: 'callyoo-2b8ca',
    storageBucket: 'callyoo-2b8ca.appspot.com',
    iosClientId: '832180320682-565mve6f6uebdve1l0moq7o0dc20p16e.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
